import { Prisma } from "../../generated/prisma/client.js";
import { BadRequestError, InternalServerError } from "../../common/errors/AppError.js";
import { reportsRepository } from "./reports.repository.js";
import { toUtcDate, type BalanceSheetQuery, type ProfitLossQuery, type TrialBalanceQuery } from "./reports.validation.js";
import type { ReportAccount, TrialBalance } from "./reports.types.js";

const zero = () => new Prisma.Decimal(0);
const money = (v: Prisma.Decimal) => v.toFixed(2);
export class ReportsService {
  async trialBalance(q: TrialBalanceQuery): Promise<TrialBalance> { const from = q.from ? toUtcDate(q.from) : undefined; const to = q.to ? toUtcDate(q.to) : undefined; await this.assertBalanced(from, to); const [totals, accounts] = await Promise.all([reportsRepository.accountTotals(from, to), reportsRepository.accounts()]); const byId = new Map(totals.map((t) => [t.account_id, t])); const rows: ReportAccount[] = accounts.map((a) => { const t = byId.get(a.id) ?? { debit: zero(), credit: zero() }; return { account_id: a.id, account_code: a.code, account_name: a.name, account_type: a.type, debit: money(t.debit), credit: money(t.credit), balance: money(t.debit.minus(t.credit)) }; }).filter((a) => a.debit !== "0.00" || a.credit !== "0.00"); return { accounts: rows, total_debit: money(totals.reduce((s, t) => s.plus(t.debit), zero())), total_credit: money(totals.reduce((s, t) => s.plus(t.credit), zero())) }; }
  async profitLoss(q: ProfitLossQuery) { const from = toUtcDate(q.from); const to = toUtcDate(q.to); await this.assertBalanced(from, to); const tb = await this.trialBalance(q); const revenue = tb.accounts.filter((a) => a.account_type === "revenue").map((a) => ({ ...a, balance: money(new Prisma.Decimal(a.credit).minus(a.debit)) })); const expenses = tb.accounts.filter((a) => a.account_type === "expense").map((a) => ({ ...a, balance: money(new Prisma.Decimal(a.debit).minus(a.credit)) })); const totalRevenue = revenue.reduce((s, a) => s.plus(a.balance), zero()); const totalExpenses = expenses.reduce((s, a) => s.plus(a.balance), zero()); return { revenue, expenses, totalRevenue: money(totalRevenue), totalExpenses: money(totalExpenses), netProfit: money(totalRevenue.minus(totalExpenses)), netLoss: totalRevenue.lt(totalExpenses) ? money(totalExpenses.minus(totalRevenue)) : "0.00" }; }
  async balanceSheet(q: BalanceSheetQuery) { const asOf = toUtcDate(q.as_of); await this.assertBalanced(undefined, asOf); const tb = await this.trialBalance({ to: q.as_of }); const assets = tb.accounts.filter((a) => a.account_type === "asset").map((a) => ({ ...a, balance: money(new Prisma.Decimal(a.debit).minus(a.credit)) })); const liabilities = tb.accounts.filter((a) => a.account_type === "liability").map((a) => ({ ...a, balance: money(new Prisma.Decimal(a.credit).minus(a.debit)) })); const equity = tb.accounts.filter((a) => a.account_type === "equity").map((a) => ({ ...a, balance: money(new Prisma.Decimal(a.credit).minus(a.debit)) })); const revenue = tb.accounts.filter((a) => a.account_type === "revenue").reduce((s, a) => s.plus(new Prisma.Decimal(a.credit).minus(a.debit)), zero()); const expenses = tb.accounts.filter((a) => a.account_type === "expense").reduce((s, a) => s.plus(new Prisma.Decimal(a.debit).minus(a.credit)), zero()); const earnings = revenue.minus(expenses); if (!earnings.eq(0)) equity.push({ account_id: "current-earnings", account_code: "", account_name: "Current earnings", account_type: "equity", debit: "0.00", credit: money(earnings.gt(0) ? earnings : zero()), balance: money(earnings) }); const totalAssets = assets.reduce((s, a) => s.plus(a.balance), zero()); const totalLiabilities = liabilities.reduce((s, a) => s.plus(a.balance), zero()); const totalEquity = equity.reduce((s, a) => s.plus(a.balance), zero()); const difference = totalAssets.minus(totalLiabilities.plus(totalEquity)); return { assets, liabilities, equity, totalAssets: money(totalAssets), totalLiabilities: money(totalLiabilities), totalEquity: money(totalEquity), isBalanced: difference.eq(0), difference: money(difference) }; }
  private async assertBalanced(from?: Date, to?: Date) { const ids = await reportsRepository.unbalancedEntries(from, to); if (ids.length) throw new BadRequestError(`Posted journal entries are unbalanced: ${ids.slice(0, 10).join(", ")}${ids.length > 10 ? " and more" : ""}`); }
}
export const reportsService = new ReportsService();
