import { Prisma } from "../../generated/prisma/client.js";
import { prisma } from "../../lib/prisma.js";
import { ConflictError, InternalServerError, NotFoundError } from "../../common/errors/AppError.js";
import { logger } from "../../config/logger.js";
import type { CreateTaxRuleInput, TaxRuleQuery, UpdateTaxRuleInput } from "./taxes.validation.js";

const include = { verifiedByUser: { select: { id: true, name: true, email: true } }, createdByUser: { select: { id: true, name: true, email: true } } } as const;
export type TaxRuleRecord = Prisma.TaxRuleGetPayload<{ include: typeof include }>;

export class TaxesRepository {
  async create(input: CreateTaxRuleInput, actorId: string): Promise<TaxRuleRecord> { try { return await prisma.taxRule.create({ data: { tax_type: input.tax_type, rate: new Prisma.Decimal(input.rate), effective_from: input.effective_from, effective_to: input.effective_to ?? null, notes: input.notes ?? null, created_by_user_id: actorId }, include }); } catch (error) { return this.writeError(error, "Failed to create tax rule"); } }
  async findAll(query: TaxRuleQuery): Promise<{ items: TaxRuleRecord[]; total: number }> { try { const where: Prisma.TaxRuleWhereInput = { ...(query.tax_type ? { tax_type: query.tax_type } : {}), ...(query.include_inactive ? {} : { is_active: true }), ...(query.verified_only ? { verified_by_accountant: true } : {}) }; const [items, total] = await prisma.$transaction([prisma.taxRule.findMany({ where, include, orderBy: [{ effective_from: "desc" }, { created_at: "desc" }], skip: (query.page - 1) * query.limit, take: query.limit }), prisma.taxRule.count({ where })]); return { items, total }; } catch (error) { logger.error({ err: error }, "Failed to list tax rules"); throw new InternalServerError("Failed to list tax rules"); } }
  async findById(id: string): Promise<TaxRuleRecord | null> { try { return await prisma.taxRule.findUnique({ where: { id }, include }); } catch (error) { logger.error({ err: error, taxRuleId: id }, "Failed to fetch tax rule"); throw new InternalServerError("Failed to fetch tax rule"); } }
  async findApplicable(taxType: string, date: Date): Promise<TaxRuleRecord | null> { try { return await prisma.taxRule.findFirst({ where: { tax_type: taxType as never, is_active: true, verified_by_accountant: true, effective_from: { lte: date }, OR: [{ effective_to: null }, { effective_to: { gte: date } }] }, orderBy: { effective_from: "desc" }, include }); } catch (error) { logger.error({ err: error, taxType, date }, "Failed to find applicable tax rule"); throw new InternalServerError("Failed to find applicable tax rule"); } }
  async history(taxType: string): Promise<TaxRuleRecord[]> { try { return await prisma.taxRule.findMany({ where: { tax_type: taxType as never }, include, orderBy: { effective_from: "desc" } }); } catch (error) { logger.error({ err: error, taxType }, "Failed to fetch tax rule history"); throw new InternalServerError("Failed to fetch tax rule history"); } }
  async update(id: string, input: UpdateTaxRuleInput, actorId: string): Promise<TaxRuleRecord> { try { const data: Prisma.TaxRuleUpdateInput = { ...(input.rate !== undefined ? { rate: new Prisma.Decimal(input.rate) } : {}), ...(input.effective_to !== undefined ? { effective_to: input.effective_to } : {}), ...(input.notes !== undefined ? { notes: input.notes } : {}), ...(input.verified_by_accountant !== undefined ? { verified_by_accountant: input.verified_by_accountant, verified_at: input.verified_by_accountant ? new Date() : null, verifiedByUser: input.verified_by_accountant ? { connect: { id: actorId } } : { disconnect: true } } : {}), updated_at: new Date() }; return await prisma.taxRule.update({ where: { id }, data, include }); } catch (error) { return this.writeError(error, "Failed to update tax rule"); } }
  async verify(id: string, verified: boolean, actorId: string): Promise<TaxRuleRecord> { try { return await prisma.taxRule.update({ where: { id }, data: { verified_by_accountant: verified, verified_at: verified ? new Date() : null, verifiedByUser: verified ? { connect: { id: actorId } } : { disconnect: true }, updated_at: new Date() }, include }); } catch (error) { return this.writeError(error, "Failed to verify tax rule"); } }
  async archive(id: string): Promise<TaxRuleRecord> { try { return await prisma.taxRule.update({ where: { id }, data: { is_active: false, effective_to: new Date(), deleted_at: new Date(), updated_at: new Date() }, include }); } catch (error) { return this.writeError(error, "Failed to archive tax rule"); } }
  async audit(input: { user_id: string; action: string; entity_id: string; old_value?: Record<string, unknown>; new_value?: Record<string, unknown> }) { try { const data: Prisma.AuditLogCreateInput = { user_id: input.user_id, action: input.action, entity_type: "TaxRule", entity_id: input.entity_id, ...(input.old_value ? { old_value: input.old_value as Prisma.InputJsonValue } : {}), ...(input.new_value ? { new_value: input.new_value as Prisma.InputJsonValue } : {}) }; await prisma.auditLog.create({ data }); } catch (error) { logger.error({ err: error, taxRuleId: input.entity_id }, "Failed to write tax rule audit log"); } }
  private writeError(error: unknown, message: string): never { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw new ConflictError("A tax rule already exists for this tax type and effective date"); if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") throw new NotFoundError("Tax rule was not found"); logger.error({ err: error }, message); throw new InternalServerError(message); }
}
export const taxesRepository = new TaxesRepository();
