"use client";

import { useState } from "react";
import { ArrowRight, Eye, EyeOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export function RegisterForm() { const [showPassword, setShowPassword] = useState(false); return <Card className="auth-card"><CardContent className="p-6 sm:p-8"><form className="space-y-4" action="#" method="post"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="first-name">First name</Label><Input id="first-name" name="firstName" placeholder="Alex" autoComplete="given-name" required /></div><div className="space-y-2"><Label htmlFor="last-name">Last name</Label><Input id="last-name" name="lastName" placeholder="Morgan" autoComplete="family-name" required /></div></div><div className="space-y-2"><Label htmlFor="company">Company name</Label><Input id="company" name="company" placeholder="Your company" autoComplete="organization" required /></div><div className="space-y-2"><Label htmlFor="register-email">Work email</Label><Input id="register-email" name="email" type="email" placeholder="you@company.com" autoComplete="email" required /></div><div className="space-y-2"><Label htmlFor="register-password">Create password</Label><div className="relative"><Input id="register-password" name="password" type={showPassword ? "text" : "password"} placeholder="At least 8 characters" minLength={8} autoComplete="new-password" className="pr-11" required /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword((value) => !value)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-secondary">{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></div><label className="flex items-start gap-2 pt-1 text-xs leading-5 text-slate-500"><input type="checkbox" name="terms" className="mt-1 h-4 w-4 shrink-0 accent-[var(--primary)]" required />I agree to the Billora terms of service and privacy policy.</label><Button type="submit" className="mt-2 h-11 w-full">Create account <ArrowRight size={16} /></Button></form></CardContent></Card>; }
