import { BadRequestError, ConflictError, NotFoundError } from "../../common/errors/AppError.js";
import { bankAccountsRepository, type BankAccountRecord } from "./bankaccounts.repository.js";
import type { BankAccountQuery, CreateBankAccountInput, UpdateBankAccountInput } from "./bankaccounts.validation.js";

export class BankAccountsService {
  async list(query: BankAccountQuery) { return bankAccountsRepository.findAll(query); }
  async get(id: string): Promise<BankAccountRecord> { const item = await bankAccountsRepository.findById(id); if (!item) throw new NotFoundError(`Bank account with ID '${id}' not found`); return item; }
  async create(input: CreateBankAccountInput, actorId: string) { const account = await bankAccountsRepository.findGlAccount(input.gl_account_id); if (!account) throw new BadRequestError("GL account was not found"); if (account.type !== "asset") throw new BadRequestError("Bank accounts must use an asset GL account"); if (!account.is_active) throw new ConflictError("The GL account is inactive"); if (await bankAccountsRepository.linkedAccount(input.gl_account_id)) throw new ConflictError("This GL account is already linked to a bank account"); const created = await bankAccountsRepository.create(input); await bankAccountsRepository.audit({ user_id: actorId, action: "BANK_ACCOUNT_CREATED", entity_id: created.id, new_value: { name: created.name, bank_name: created.bank_name, currency: created.currency, gl_account_id: created.gl_account_id } }); return created; }
  async update(id: string, input: UpdateBankAccountInput, actorId: string) { const current = await this.get(id); const updated = await bankAccountsRepository.update(current.id, input); await bankAccountsRepository.audit({ user_id: actorId, action: "BANK_ACCOUNT_UPDATED", entity_id: id, old_value: { name: current.name, bank_name: current.bank_name, currency: current.currency }, new_value: { name: updated.name, bank_name: updated.bank_name, currency: updated.currency } }); return updated; }
  async remove(id: string, actorId: string) { const current = await this.get(id); if (await bankAccountsRepository.transactionCount(current.gl_account_id) > 0) throw new ConflictError("Bank account cannot be deleted because it has accounting transactions"); const removed = await bankAccountsRepository.deactivate(id); await bankAccountsRepository.audit({ user_id: actorId, action: "BANK_ACCOUNT_DEACTIVATED", entity_id: id, old_value: { is_active: true }, new_value: { is_active: false } }); return removed; }
  async getBalance(id: string) { const account = await this.get(id); const balance = await bankAccountsRepository.balance(account.gl_account_id); return { bank_account_id: account.id, currency: account.currency, ...Object.fromEntries(Object.entries(balance).map(([key, value]) => [key, value.toFixed(2)])) }; }
}
export const bankAccountsService = new BankAccountsService();
