import { Prisma } from "../../generated/prisma/client.js";
import { prisma } from "../../lib/prisma.js";
import { InternalServerError } from "../../common/errors/AppError.js";
import { logger } from "../../config/logger.js";
import type { AuditExportQuery, AuditQuery, AuditSummaryQuery } from "./audit.validation.js";

export type AuditRecord = Prisma.AuditLogGetPayload<{}>;
type Scope = { userId?: string; founder: boolean };
const whereFor = (q: AuditQuery | AuditExportQuery, scope: Scope): Prisma.AuditLogWhereInput => ({ ...(scope.founder && q.user_id ? { user_id: q.user_id } : {}), ...(scope.founder && q.my ? { user_id: scope.userId } : {}), ...(!scope.founder ? { user_id: scope.userId } : {}), ...(q.entity_type ? { entity_type: q.entity_type } : {}), ...(q.entity_id ? { entity_id: q.entity_id } : {}), ...(q.action ? { action: q.action } : {}), ...(q.action_status ? { action_status: q.action_status } : {}), ...(q.date_from || q.date_to ? { created_at: { ...(q.date_from ? { gte: q.date_from } : {}), ...(q.date_to ? { lte: q.date_to } : {}) } } : {}) });

export class AuditRepository {
  async list(q: AuditQuery, scope: Scope) { try { const where = whereFor(q, scope); const [items, total] = await prisma.$transaction([prisma.auditLog.findMany({ where, orderBy: [{ created_at: "desc" }, { id: "desc" }], skip: (q.page - 1) * q.limit, take: q.limit }), prisma.auditLog.count({ where })]); return { items, total }; } catch (error) { logger.error({ err: error }, "Failed to list audit logs"); throw new InternalServerError("Failed to list audit logs"); } }
  async entity(type: string, id: string, scope: Scope) { try { return prisma.auditLog.findMany({ where: { entity_type: type, entity_id: id, ...(!scope.founder ? { user_id: scope.userId } : {}) }, orderBy: [{ created_at: "asc" }, { id: "asc" }] }); } catch (error) { logger.error({ err: error }, "Failed to fetch entity audit history"); throw new InternalServerError("Failed to fetch entity audit history"); } }
  async userActivity(userId: string, scope: Scope) { try { return prisma.auditLog.findMany({ where: { user_id: userId, ...(!scope.founder ? { user_id: scope.userId } : {}) }, orderBy: [{ created_at: "desc" }, { id: "desc" }], take: 1000 }); } catch (error) { logger.error({ err: error }, "Failed to fetch user audit history"); throw new InternalServerError("Failed to fetch user audit history"); } }
  async summary(q: AuditSummaryQuery, scope: Scope) { try { const date = q.date_from || q.date_to ? { ...(q.date_from ? { gte: q.date_from } : {}), ...(q.date_to ? { lte: q.date_to } : {}) } : undefined; const where: Prisma.AuditLogWhereInput = { ...(date ? { created_at: date } : {}), ...(q.entity_type ? { entity_type: q.entity_type } : {}), ...(!scope.founder ? { user_id: scope.userId } : {}) }; const [total, failed, byAction, byEntity, byUser] = await prisma.$transaction([prisma.auditLog.count({ where }), prisma.auditLog.count({ where: { ...where, action_status: "failed" } }), prisma.auditLog.groupBy({ by: ["action"], where, _count: { _all: true } }), prisma.auditLog.groupBy({ by: ["entity_type"], where, _count: { _all: true } }), prisma.auditLog.groupBy({ by: ["user_id"], where, _count: { _all: true } })]); return { total, failed, by_action: byAction, by_entity: byEntity, by_user: byUser }; } catch (error) { logger.error({ err: error }, "Failed to summarize audit logs"); throw new InternalServerError("Failed to summarize audit logs"); } }
  async export(q: AuditExportQuery, scope: Scope) { try { return await prisma.auditLog.findMany({ where: whereFor(q, scope), orderBy: [{ created_at: "asc" }, { id: "asc" }], take: 10000 }); } catch (error) { logger.error({ err: error }, "Failed to export audit logs"); throw new InternalServerError("Failed to export audit logs"); } }
}
export const auditRepository = new AuditRepository();
